NewPoll/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
import polls, accounts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('polls/', include('polls.urls', namespace='polls')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('list/', views.poll_view, name='poll_view'),
    path('add/', views.add_poll, name='add'),
    path('edit/<int:poll_id>', views.edit_poll, name='edit_poll'),
    path('edit/<int:poll_id>/add/choice' , views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>', views.edit_choice, name='edit_choice'),
    path('delete/choice/<int:choice_id>', views.choice_delete, name='choice_delete'),
    path('delete/poll/<int:poll_id>/', views.poll_delete, name='poll_delete'),
    # polls/details/1
    # <int:poll_id> is to get the id of the poll, and poll_id typed here first
    # <int> is not requierd , it's optionally, but better to put if looking for intgers only
    # to know more about <int> search for python Path converters
    path('details/<int:poll_id>', views.poll_detailes, name='poll_details'),
    path('details/<int:poll_id>/vote', views.poll_vote, name='vote')
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Poll(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1) # attach the user to the poll
    text = models.CharField(max_length=255)
    number = models.CharField(max_length=255)

    # to make the text appears on the admin panel
    def __str__(self):
        return self.text # this text is the previous variable


    def user_can_vote(self, user):
        user_votes = user.vote_set.all()
        qs = user_votes.filter(poll=self)
        if qs.exists():
            return False
        return True

    @property # to be able to call it directly anywhere
    def num_votes(self):
        return self.vote_set.count()

    def get_percentages(self):
        resault = []
        for choice in self.choices_set.all(): # self refering to Poll class
            dict = {}
            dict['text'] = choice.choice_text
            dict['num_choice'] = choice.num_choices
            if not self.num_votes:
                dict['percentage'] = 0
            else:
                dict['percentage'] = choice.num_choices / self.num_votes * 100
            resault.append(dict)
        return resault


class Choices(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE) # connecting with the previous class
    choice_text = models.CharField(max_length=250) # adding the votes choices into it
    # vote = models.IntegerField(default=0)   # counting how many times the votes happened

    def __str__(self):
        return ' {} - {} '.format(self.poll.text, self.choice_text)
        '''
            previous return statement makes it appear on the shell like this:

            <QuerySet [<Choices:  Te gusta Django ? - Si - 0>, <Choices:  Te gusta Django ? - Si, Claro - 0>]>

            using:
            var = Poll.objects.first() # gets the first object from polls with it's answers
            var.choices_set.all()      # that's what will cause the previous display
                                       # able to use var.choices_set just like var.objects

            explain:
            [<Choices:
                        Te gusta Django ? # self.question.text
                        - Si              # self.choice_text
                        - 0               # self.vote
            >]

            Able to add another choices directly from the Shell using create keyword:
                var.choices_set.create(choice_text='No, Nunca') # NOTICE choice_text


            ## NOTICE that u have to import Choices and Poll before excuting previous commands

            ## ALSO NOTICE THAT the resault of the two commands
                Choices.objects.all()
                var.choices_set.all()
               THEY are the same resaults, that's cuz of the ForeignKey statement earlier
               which connected the two classes together
        '''

    @property # to be able to call it directly anywhere
    def num_choices(self):
            return self.vote_set.count()


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choices, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice.choice_text

polls/forms.py
from django import forms
from .models import Poll, Choices

class Pollform(forms.ModelForm):
    choice1 = forms.CharField(  label='First Choice',
                                max_length=100,
                                min_length=3,
                                widget=forms.TextInput(attrs={'class':'form-control'}))

    choice2 = forms.CharField(  label='Second Choice',
                                max_length=100,
                                min_length=3,
                                widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta(): # This how we add extra stuff to a class
        model = Poll
        # fields = '__all__' # to import all variables from Poll class
        fields = ['text', 'choice1', 'choice2']

        # to style text like we did for choice1 and choice2
        # but because we don't have access to text from here and it lives in another class in models.py
        # so we have to do it the way underneath in the widgets dictionary
        widgets = {
            'text': forms.TextInput(attrs={'class':'form-control'})
        }


class EditPollForm(forms.ModelForm):

    class Meta():
        model = Poll
        fields = ['text']
        widgets = {
                    'text': forms.TextInput(attrs={'class':'form-control'})
                }


class AddPollForm(forms.ModelForm):

    class Meta():
        model = Choices
        fields = ['choice_text']

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count

# from django.conf import settings

# Local imports
from .models import Poll, Choices, Vote
from .forms import Pollform, EditPollForm, AddPollForm

# Create your views here.
# the next @login_required will not permit the user to see the polls if not logged in
# the raw CODE to do it is the folloing,
# if not request.user.is_authenticated():
#     return redirect('{}?next={}'.format(settings.LOGIN_URL, request.PATH))

@login_required
def poll_view(request):
    """
    Renders polls_list.html template which contains all the available polls
    """
    poll_txt = Poll.objects.all()
    search_term=''


    if 'text' in request.GET:
        poll_txt = poll_txt.order_by('text') #This 'text' is from Poll class in models.py

    # commented cuz i didn't create date field in the class in models.py
    # if 'date' in request.GET:
    #     poll_txt = poll_txt.order_by('-pub_date')

    if 'num_votes' in request.GET:
        poll_txt = poll_txt.annotate(Count('vote')).order_by('vote__count') # The Vote class in models.py

    if 'search' in request.GET:
        search_term = request.GET['search']
        poll_txt = poll_txt.filter(text__icontains=search_term) # text from models.py


    paginator = Paginator(poll_txt, 5) # making it 5 pages
    page = request.GET.get('page')
    poll_txt = paginator.get_page(page)

    get_dict_copy = request.GET.copy() # Getting a copy of this dictionary
            # removing page from the dict cuz we already have it in the polls_list
            # and will add params next to page anyway
            # then urlencode to make it looks like normal string
    params = get_dict_copy.pop('page', True) and get_dict_copy.urlencode()
    params = '&'+params

    context = {
    'poll_txt':poll_txt,
    'params':params,
    'search_term':search_term,
    }
    return render(request, 'polls/polls_list.html',  context)

@login_required
def add_poll(request):
    if request.method == 'POST' :
        form = Pollform(request.POST)
        new_poll = form.save(commit=False) # commit=False is the way to tell django not to commit the data
                                          # to the database now, wait untill we finish and will commit it by us
        new_poll.number = 123 #just anything random
        new_poll.owner = request.user # attach the created poll to the user who made it
        new_poll.save() # now we saving it manually
                        # will add to Poll Class, see it in Admin page

        # to add the polls user made to the data base and to the Choices class in models.py
        # print(form.cleaned_data) to see inside form.cleaned_data
        # new_poll returns the text field by default

        choice1 = Choices(poll = new_poll, choice_text=form.cleaned_data['choice1']).save()
        choice2 = Choices(poll = new_poll, choice_text=form.cleaned_data['choice2']).save()

        messages.success(request,
                            'Poll has been updated successfully',
                            extra_tags='alert alert-success alert-dismissible fade show') # Bootstrap classes

        return redirect('polls:poll_view')
    else:
        form = Pollform()
    return render(request, 'polls/add_poll.html', context={'form':form})

@login_required
def poll_delete(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    if request.user != poll.owner:
        redirect('/')
    if request.method == 'POST':
        poll.delete()
        messages.success(
            request,
            'Poll has been deleted successfully',
            extra_tags='alert alert-success alert-dismissible fade show'
        )
        return redirect('polls:poll_view')
    return render(request, 'polls/delete_poll.html', {'poll': poll})


@login_required
def edit_poll(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    # to check if it's user who's trying to edit it
    # if it's another user, will redirect him to home page
    if request.user != poll.owner:
        return redirect('/')

    # to edit the choosen poll
    # grapping the text field from Poll class with EditPollForm
    # then adding a new value into it in edit_poll.html
    # then passing it again using the ifs below

    if request.method == 'POST':
        form = EditPollForm(request.POST, instance=poll)
        if form.is_valid():
            form.save()
            messages.success(request,
                            'Poll has been Edited successfully',
                            extra_tags='alert alert-success alert-dismissible fade show')
            return redirect('polls:poll_view')
    else:
        form = EditPollForm(instance=poll)

    return render(request, 'polls/edit_poll.html', {'form':form, 'poll':poll})


@login_required
def add_choice(request, poll_id):
        poll = get_object_or_404(Poll, id=poll_id)
        # to check if it's user who's trying to edit it
        # if it's another user, will redirect him to home page
        if request.user != poll.owner:
            return redirect('/')

        if request.method == 'POST':
            form = AddPollForm(request.POST)
            if form.is_valid():
                new_choice = form.save(commit=False)
                new_choice.poll = poll
                # new_choice.poll, poll is from Choices class from models.py
                # = poll , poll is the variable above
                new_choice.save()
                messages.success(request,
                                'Choice has been Added successfully',
                                extra_tags='alert alert-success alert-dismissible fade show')
                return redirect('polls:poll_view')
        else:
            form = AddPollForm()

        return render(request, 'polls/add_choice.html', {'form':form})


@login_required
def edit_choice(request, choice_id):
        choice = get_object_or_404(Choices, id=choice_id)
        poll = get_object_or_404(Poll, id=choice.poll.id)

        if request.user != poll.owner:
            return redirect('/')

        if request.method == 'POST':
            form = AddPollForm(request.POST, instance=choice)
            if form.is_valid():
                new_choice = form.save(commit=False)
                new_choice.poll = poll
                # new_choice.poll, poll is from Choices class from models.py
                # = poll , poll is the variable above
                new_choice.save()
                messages.success(request,
                                'Choice has been Edited successfully',
                                extra_tags='alert alert-success alert-dismissible fade show')
                return redirect('polls:poll_view')
        else:
            form = AddPollForm(instance=choice)

        return render(request, 'polls/add_choice.html', {'form':form,'choice':choice, 'edit_mode':True} )

@login_required
def choice_delete(request, choice_id):
        choice = get_object_or_404(Choices, id=choice_id)
        poll = get_object_or_404(Poll, id=choice.poll.id)

        if request.user != poll.owner:
            return redirect('/')

        if request.method == 'POST':
            choice.delete()
            messages.success(request,
                                'Choice has been Edited successfully',
                                extra_tags='alert alert-success alert-dismissible fade show')
            return redirect('polls:poll_view')

        return render(request, 'polls/delete_choice.html', {'choice':choice} )



@login_required
def poll_detailes(request, poll_id): # poll_id passed from urls.py file
    '''
    Renders poll_details.html which allow the user to vote
    '''
    poll_choice = get_object_or_404(Poll, id=poll_id) # id gets it's value from the polls_list.html

    # get_object_or_404 returns a 404 page if it couldn't get the id instead of displaying the server error page
    # to display server error page use:
        # poll_choice = Poll.objects.get(id=poll_id)

    user_can_vote = poll_choice.user_can_vote(request.user)
    resaults = poll_choice.get_percentages()

    context = {
        'poll_choice':poll_choice,
        'user_can_vote':user_can_vote,
        'resaults':resaults
    }

    # a way to check the request whether it's a POST or a GET from polls_detailes.html
    # if request.method == 'POST':
    #      print(request.POST)
    #     print('you POSTED !!!')
    # if request.method == 'GET':
    #     print(request.GET)
    #     print('you GET')

    return render(request, 'polls/polls_detailes.html', context)

@login_required
def poll_vote(request, poll_id):
    poll_choice = get_object_or_404(Poll, id=poll_id)
    choice_id = request.POST.get('choice', None) # this choice is the key from a dictionary caused by the POST method
                                           # here we are getting the value of that key which will be the id
                                           # from form of the polls_details.html
                                           # print(request.POST) #putting it first in this def to see that dict
                                           # POST[''] using those brackets is how to get the value of a key from dict
    # use .get() above to check if 'choice'
    # is available or not in the POST dict
    # .get() is a built-in python method

    if not poll_choice.user_can_vote(request.user):
                messages.error(request, 'You have already voted here !!!')
                return HttpResponseRedirect(reverse('polls:poll_details', args=(poll_id,)))

    if choice_id: # check if choice_id is not a None

polls/templates/polls/add_choice.html
{% extends 'index.html'%}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1 class="text-center" style='margin:5% 0 5% 0'>
        {% if edit_mode %}
          Edit a Choice
        {% else %}
          Add a Choice
        {% endif %}
         using the form below !!
      </h1>
      <form action="" method="post"> <!-- action is empty which means we gonna Post to the same page we are in -->
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group"> <!-- this form group is for Bootstrap -->
          {{ field.errors }}    <!-- will dispaly any errors if it exists -->
          {{ field.label_tag }} <!-- will cleate a whole <label for=""></label> for us -->
          {{ field }}           <!-- this creates the input place, just like <input type="text" name="" value=""> -->
        </div>
        {% endfor %}
        <input type="submit" class="btn btn-primary" name="login" value="Submit">
        {% if edit_mode %}
          <a href="{% url 'polls:choice_delete' choice_id=choice.id %}" 
             class="btn btn-danger">Delete <i class="far fa-trash-alt"></i>
          </a>
        {% endif %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

polls/templates/polls/add_poll.html
{% extends 'index.html'%}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1 class="text-center" style='margin:5% 0 5% 0'>Add The Polls That You Want To Choose From !!</h1>
      <form action="" method="post"> <!-- action is empty which means we gonna Post to the same page we are in -->
        {% csrf_token%}
        {% for field in form %}
        <div class="form-group"> <!-- this form group is for Bootstrap -->
          {{ field.errors }}    <!-- will dispaly any errors if it exists -->
          {{ field.label_tag }} <!-- will cleate a whole <label for=""></label> for us -->
          {{ field }}           <!-- this creates the input place, just like <input type="text" name="" value=""> -->
        </div>
        {% endfor %}
        <input type="submit" class="btn btn-primary" name="login" value="Submit">
      </form>
    </div>
  </div>
</div>
{% endblock %}

polls/templates/polls/delete_choice.html
{% extends 'index.html' %}
{% block content %}
{% csrf_token %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 text-center">
      <form action="" method="post">
        <input type="submit" class="btn btn-danger" value="Confirm Deleting !!">
      </form>
    </div>
  </div>
</div>
{% endblock %}

polls/templates/polls/delete_poll.html
{% extends 'index.html' %}
{% block content %}
{% csrf_token %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 text-center">
      <form action="" method="post">
        <input type="submit" class="btn btn-danger" value="Confirm Deleting !!">
      </form>
    </div>
  </div>
</div>
{% endblock %}

polls/templates/polls/edit_poll.html
{% extends 'index.html'%}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1 class="text-center" style='margin:5% 0 5% 0'>Edit This Poll using the form below !!</h1>
      <form action="" method="post"> <!-- action is empty which means we gonna Post to the same page we are in -->
        {% csrf_token%}
        {% for field in form %}
        <div class="form-group"> <!-- this form group is for Bootstrap -->
          {{ field.errors }}    <!-- will dispaly any errors if it exists -->
          {{ field.label_tag }} <!-- will cleate a whole <label for=""></label> for us -->
          {{ field }}           <!-- this creates the input place, just like <input type="text" name="" value=""> -->
        </div>
        {% endfor %}
        <input type="submit" class="btn btn-primary" name="login" value="Submit">
        <a href="{% url 'polls:add_choice' poll_id=poll.id %}" class="btn btn-warning"> Add Choice </a>
        <a href="{% url 'polls:poll_delete' poll.id %}"
           class="btn btn-danger">Delete Poll <i class="far fa-trash-alt"></i>
        </a>
      </form>
      <h3 class="text-center">Choices</h3>
      {% for choice in poll.choices_set.all %}
        <p><a href="{% url 'polls:edit_choice' choice_id=choice.id %}"><i class="fas fa-edit"></i></a>{{choice.choice_text }}</p>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

polls/templates/polls/polls_detailes.html
{% extends 'index.html' %}


{% block content %}

<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1>Welcome to detailes page !!!</h1>

      <!-- to dispaly the error message in the same page if the user didn't vote  -->
      {% if messages %} <!-- that's if messages in views.py def poll_vote became True -->
      <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}><h1>{{ message }}</h1></li>
        <!-- above if statement to add a calss dynamically to the li with the message  -->
        {% endfor %}
      </ul>
      {% endif %}

      <p>
        {{ poll_choice }} <!-- poll_choice is a variable from views.py def poll_details -->
        -
        {{ poll_choice.num_votes }} <!-- for num_votes check class Poll in models.py -->
        {% if poll_choice.num_votes > 1 %} votes {% else %} vote {% endif %}
      </p>

      <form action="{% url 'polls:vote' poll_choice.id %}" method="post">

        <!-- this action="{% url ...." is for going into another page displaying statistics or number of voters
          or anything else i want to display after the user hits VOTE button  -->

          {% csrf_token %}
          {% for choice in poll_choice.choices_set.all %}
                <input  type="radio" name="choice"
                        id='choice {{ forloop.counter }}'
                        value="{{ choice.id }}" />

          <!-- name='choice ==> just a name for now -->
          <!-- id='choice.....' ==> count through every choice to know where to start next,
            resault will be: choice 1, choice 2, choice 3, etc... -->
            <!-- value='{{ choice.id }}' ==> get the choice id of every count,
              every choice of the previous will be attached to it's id -->

                <label for="choice {{ forloop.counter }}" > <!-- to make the label knows where to go to, in front of which radio -->
                {{ choice.choice_text }}
                </label>
                <br>
          {% endfor %}
          <input type="submit" value="Vote"
          class="btn btn-primary"
          {% if not user_can_vote %}disabled{% endif %}
          />
      </form>
      <br>
      {% for choice_percentage in poll_choice.get_percentages %}
        {{ choice_percentage.text }} - {{ choice_percentage.num_choice }} Choices
        <div class="progress">
          <div  class="progress-bar"
                role="progressbar" style="width: {{ choice_percentage.percentage }}%;"
                aria-valuenow="{{ choice_percentage.percentage }}"
                aria-valuemin="0" aria-valuemax="100">{{ choice_percentage.percentage }}%
          </div>
        </div><br>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

polls/templates/polls/polls_list.html
{% extends 'index.html' %}
{% load static %}

<!-- {% block polls_detailes_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/polls_css.css' %}">
{% endblock %} -->


{% block content%}

<div class="container">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <div class="poll_txt">

        <h1 class="text-center" >NewPoll List page !!!</h1> <!-- this class is a Bootstrap thing -->

        <!-- to print out the status of the current user -->
        <!--
         to see the all request available objects use :
         for key in request.__dict__:
              print(key)
         you will see user among them
        -->

        <h2 class="text-center" > <!-- this class is a Bootstrap thing -->
            {% if request.user.is_authenticated %}
              Hey there {{ request.user }}
            {% else %}
              You are not logged in
            {% endif %}
        </h2>

        {% if messages %} <!-- that's if messages in views.py def poll_vote became True -->
          {% for message in messages %}
          <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
            {{ message }}
            <!-- all this coppied from Bottstarp -->
            <button type="button" class='close' data-dismiss='alert' aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <!-- above if statement to add a calss dynamically to the li with the message  -->
          {% endfor %}
        {% endif %}

        <a href=" {% url 'polls:add' %}" class="btn btn-primary"
           style='margin-bottom:5px;color:white;font-weight:bold'>
          Add
          <i class="fas fa-plus"></i> <!-- An icon from fontawesome -->
        </a>

        <!-- ordering buttons  -->
        <div class="ordering" style='float: inline-end;'>
          <a href="?text=True" class="btn btn-{% if 'text' in request.GET %}warning{% else %}primary{% endif %}"
              style='margin-bottom:5px;color:white;font-weight:bold'>
              Text
          </a>
          <a href="?date=True" class="btn btn-{% if 'date' in request.GET %}warning{% else %}primary{% endif %}"
              style='margin-bottom:5px;color:white;font-weight:bold'>
              Publish Date
          </a>
          <a href="?num_votes=True" class="btn btn-{% if 'num_votes' in request.GET %}warning{% else %}primary{% endif %}"
              style='margin-bottom:5px;color:white;font-weight:bold'>
              Num_Votes
          </a>
        </div>

        <form class="form-inline my-2 my-lg-2">
          <input class="form-control mr-sm-2" type="search" placeholder="Search"
                aria-label="Search" name='search' value="{{search_term}}">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>



        <ul class="list-group">
          <!-- poll_txt is a variable from views.py, def poll_view -->
          {% for poll in poll_txt %}

          <li class="list-group-item">
            <a href="{% url 'polls:poll_details' poll_id=poll.id %}">{{ poll }}</a>
            {% if request.user == poll.owner %} <!-- show it to logged in user
                                                     only if he was the one who created it -->
              <a href="{% url 'polls:edit_poll' poll_id=poll.id %}" class="float-right"><i class="fas fa-edit"></i></a>
            {% endif %}
          </li><!-- namespace first then name -->
          <!-- poll_id gets the id of the clicked question and pass it to views.py  -->


          <!-- {% for choice in poll.choices_set.all %}
            <li>{{ choice.choice_text }}</li>
            {% endfor %} -->

            {% endfor %}
        </ul>
        <div class="pagination">
          <span class='step-links'>
            {% if poll_txt.has_previous %}
            <a href="?page={{ poll_txt.previous_page_number }}{{params}}">&laquo; Previous</a>
            <!-- @laquo; and &raquo; to add this sign >> << next to the word-->
              <a href="?page=1{{params}}">First </a>
            {% endif %}
            <span class="current">
              Page {{ poll_txt.number }} of {{ poll_txt.paginator.num_pages }}.
            </span>
            {% if poll_txt.has_next %}
            <a href="?page={{ poll_txt.paginator.num_pages }}{{params}}">Last</a>
              <a href="?page={{ poll_txt.next_page_number }}{{params}}">Next  &raquo;</a>
            {% endif %}
          </span>
        </div>

        <!-- i can do it that way, and i have to copy and paste it into all spans above
              IN the href next to ?page..... -->

        <!-- {% for key, value in request.GET.items %}
          {% if key != 'page' %}
            {{key}} = {{value}}
          {% endif %}
        {% endfor %} -->
      </div>
    </div>
  </div>
</div>

{% endblock %}