NewPoll/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
import polls, accounts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('polls/', include('polls.urls', namespace='polls')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_registration, name='register')
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('list/', views.poll_view, name='poll_view'),
    path('add/', views.add_poll, name='add'),
    path('edit/<int:poll_id>', views.edit_poll, name='edit_poll'),
    path('edit/<int:poll_id>/add/choice' , views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>', views.edit_choice, name='edit_choice'),
    path('delete/choice/<int:choice_id>', views.choice_delete, name='choice_delete'),
    path('delete/poll/<int:poll_id>/', views.poll_delete, name='poll_delete'),
    # polls/details/1
    # <int:poll_id> is to get the id of the poll, and poll_id typed here first
    # <int> is not requierd , it's optionally, but better to put if looking for intgers only
    # to know more about <int> search for python Path converters
    path('details/<int:poll_id>', views.poll_detailes, name='poll_details'),
    path('details/<int:poll_id>/vote', views.poll_vote, name='vote')
]

templates/home.html
{% extends 'index.html' %}

{% load static %}

{% block home_css %}
<link rel="stylesheet" type="text/css" href=" {% static 'css/home_css.css' %}" />
{% endblock %}

<!-- {{ block.super}} --><!-- this will make all content from index.html appears all the time -->



{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <div class="home_content">

        <h1>Welcome back to the NewPoll Home</h1>
        {% if user.is_authenticated %}
          <span style='margin-left:20%'> User {{ user.username }}</span>
        {% endif%}
        <h2>Your voice doesn't matter</h2>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <title> NewPoll | Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    {% block home_css %}{% endblock %}
    <!-- {% block polls_detailes_css%}{% endblock %} -->
    <!-- {% block nav_css %}{% endblock %} -->

  </head>

  <body>
      <header>
      {% include 'nav.html' %} <!-- to add the nave bar here and to all the project pages -->
      </header>
    {% block content %}<h1>default one if home_page didn't reload</h1>{% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

  </body>

</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}" style='font-weight:bold'>PollMe</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active"
         href="{% url 'home' %}" > <!-- 'home' is name='home' from NewPoll.urls -->
         Home<span class="sr-only">(current)</span>
      </a>

      <a class="nav-item nav-link" href="{% url 'polls:poll_view' %}">
        Polls</a><!-- 'polls:poll_view' is from two urls files
                      'polls' is namespace='polls' from NewPoll.urls
                      'poll_view' is name='poll_view' from polls.urls
                  -->
      <a class="nav-item nav-link" href="http://127.0.0.1:8000/admin/">Admin</a>
    </div>
      {% if user.is_authenticated %}
        <a class="nav-item nav-link ml-auto" href="{% url 'accounts:user_logout' %}"
           style='font-weight:bold; border:2px solid blue; border-radius:20% 0 20% 0'>Logout</a>
      {% else %}
        <a class="nav-item nav-link ml-auto" href="{% url 'accounts:user_login' %}"
           style='font-weight:bold; border:2px solid blue; border-radius:20% 0 20% 0'>Login</a>
      {% endif %}
  </div>
</nav>